<%@ Page Title="" Language="C#" MasterPageFile="~/TrangChu.Master" AutoEventWireup="true" CodeBehind="TTcuaHang.aspx.cs" Inherits="BaoCao.word.TTcuaHang" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style15 {
            width: 687px;
        }
        .auto-style16 {
            height: 26px;
        }
        .auto-style18 {
            width: 687px;
            height: 24px;
        }
        .auto-style19 {
            height: 24px;
        }
        .auto-style20 {
            height: 23px;
        }
       
        .auto-style28 {
            width: 62px;
            height: 14px;
        }
       
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <table style="width:100%;">
        <tr>
            <td class="auto-style19"></td>
            <td class="auto-style18">
                <p class="auto-style16" style="margin: 0px; padding: 0px; color: rgb(255, 0, 0); font-family: Arial; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);">&nbsp;</span><strong style="margin: 0px; padding: 0px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;<span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0); font-size: 22px; font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;"><span>&nbsp;</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; SHOP CÔNG NGHỆ </span></strong><span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0); font-size: 20px;"><span style="margin: 0px; padding: 0px;">MVC</span></span><span style="margin: 0px; padding: 0px;"></p>
            </td>
            </span>
            <td class="auto-style19"></td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td class="auto-style15">
                <p style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Arial; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="margin: 0px; padding: 0px;">–<span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);">SHOP CÔNG NGHỆ&nbsp;MVC&nbsp;</span>&nbsp;</strong><span style="margin: 0px; padding: 0px; color: rgb(0, 255, 0);"><strong style="margin: 0px; padding: 0px;">chuyên &nbsp;<em style="margin: 0px; padding: 0px;">mua bán &nbsp;</em>Laptop &nbsp;cũ, Laptop hư&nbsp;các dòng máy :HP, ASUS, DELL, ACER, SONY, GETWAY, FUJITSU, LENOVO….</strong></span></p>
                <p style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Arial; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="margin: 0px; padding: 0px;">–<span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);">Mua t</span></strong><span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);"><strong style="margin: 0px; padding: 0px;">ất cả&nbsp;các cấu hình máy từ</strong></span><strong style="margin: 0px; padding: 0px;">:&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(0, 255, 0);">pentum, dual core, core 2, core i3, core i5, core i7</span></strong></p>
                <p style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Arial; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="margin: 0px; padding: 0px;">–<span style="margin: 0px; padding: 0px; color: rgb(0, 255, 0);">Mua máy tính bàn cũ, máy in cũ, h</span></strong><span style="margin: 0px; padding: 0px; color: rgb(0, 255, 0);"><strong style="margin: 0px; padding: 0px;">ư&nbsp;các loại</strong></span></p>
                <p style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Arial; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="margin: 0px; padding: 0px;">–<span style="margin: 0px; padding: 0px; color: rgb(0, 255, 0);">Nh</span></strong><span style="margin: 0px; padding: 0px; color: rgb(0, 255, 0);"><strong style="margin: 0px; padding: 0px;">ận thông tin máy,báo giá&nbsp;qua&nbsp;điện thoại, tới tận nơi test máy nhanh , thanh toán tiền mặt</strong></span></p>
                <p style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Arial; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="margin: 0px; padding: 0px;">–<span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);">Đ</span></strong><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);"><strong style="margin: 0px; padding: 0px;">ặc biệt mua máy hư, máy xác, không còn sử&nbsp;dụng giá&nbsp;cao theo giá&nbsp;linh kiện cũ</strong></span></p>
                <p style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Arial; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="margin: 0px; padding: 0px;">–<span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);">Chuyên thu mua laptop t</span></strong><span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);"><strong style="margin: 0px; padding: 0px;">ại Bình Dươ</strong></span><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);">ng</span>:<em style="margin: 0px; padding: 0px;">&nbsp;Thủ&nbsp;Dầu Một, Dĩ&nbsp;An, Thuân An, Tân Uyên, Bến&nbsp;Cát, Phú Giáo, Dầu Tiếng…</em></strong></p>
                <p style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Arial; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="margin: 0px; padding: 0px;">–<span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);">Chuyên thu mua laptop t</span></strong><span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);"><strong style="margin: 0px; padding: 0px;">ạ</strong></span><strong style="margin: 0px; padding: 0px;"><span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);">i TPHCM</span><span>&nbsp;</span>:&nbsp;<em style="margin: 0px; padding: 0px;">Thủ</em></strong>&nbsp;<strong style="margin: 0px; padding: 0px;"><em style="margin: 0px; padding: 0px;">Đức, Gò&nbsp;Vấp, Q.1, Q.2, Q.3, Bình Thạnh, Tân Bình, Tân Phú, Q.12…</em></strong></p>
                <p style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Arial; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="margin: 0px; padding: 0px;">–<span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);">Thu mua laptop, máy tính, máy in t</span></strong><span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);"><strong style="margin: 0px; padding: 0px;">ận nơi, tại nhà&nbsp;giá&nbsp;cao tại TPHCM, Bình Dương,&nbsp;Đồng Nai…</strong></span></p>
                <p style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Arial; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <em style="margin: 0px; padding: 0px;"><strong style="margin: 0px; padding: 0px;">–<span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);">Nh</span></strong><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);"><strong style="margin: 0px; padding: 0px;">ận thu mua, thanh lý&nbsp;laptop cũ, mới, máy tính bàn, máy in các doanh nghiệp, công ty, trường học, tiện net, tiệm cầm&nbsp;đồ, không hạn chế&nbsp;cấu hình máy, số&nbsp;lượng tại Bình Dương, Biên Hòa-Đồng Nai, TPHCM.</strong></span></em></p>
                <p style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Arial; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="margin: 0px; padding: 0px;">–<span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);">Khi quý khách có nhu c</span></strong><span style="margin: 0px; padding: 0px; color: rgb(0, 0, 255);"><strong style="margin: 0px; padding: 0px;">ầu mua bán laptop cũ, mới, máy tính, máy in hãy liên hệ&nbsp;chúng tôi, chúng tôi luôn sẵn sàng, phục vụ&nbsp;24h, chúng tôi sẽ&nbsp;có&nbsp;mặt sau 30p tại Bình Dương, TPHCM,&nbsp;Đồng Nai…</strong></span></p>
                <p style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Arial; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="margin: 0px; padding: 0px;">–<span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);">Hình th</span></strong><span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);"><strong style="margin: 0px; padding: 0px;">ức thu mua: kiểm tra test máy nhanh, thanh toán tiền mặt 1 lần,&nbsp;đặc biệt không&nbsp;ép giá, kì&nbsp;kèo,&nbsp;&nbsp;nhiệt tình vui vẻ, thuận mua vừa bán.</strong></span></p>
                <p style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Arial; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="margin: 0px; padding: 0px;">–Bán laptop cũ giá rẻ:&nbsp;DELL, ASUS, ACER, SONY…TỪ&nbsp;CORE 2, I3, I5 , I7&nbsp;ĐẨY&nbsp;ĐỦ&nbsp;LOẠI GIÁ&nbsp;CẢ</strong></p>
                <p style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Arial; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="margin: 0px; padding: 0px;">Mọi chi tiết vui lòng liên hệ&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);">SHOP CÔNG NGHỆ&nbsp;</span></strong><span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);"><span style="margin: 0px; padding: 0px;">MVC</span></span><span style="margin: 0px; padding: 0px;"></p>
                </span>
                <p style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Arial; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);"><em style="margin: 0px; padding: 0px;"><strong style="margin: 0px; padding: 0px;">Mr. Chánh : </strong></em><span style="margin: 0px; padding: 0px;">0369797432 OR 0961089798</span></span><span style="margin: 0px; padding: 0px;"></p>
                </span>
                <p style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Arial; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="margin: 0px; padding: 0px;">Mail:&nbsp;maivanchanh321@gmail.com</strong></p>
                <p style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Arial; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="margin: 0px; padding: 0px;">&nbsp;</strong></p>
                <table class=" alignleft" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Arial; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <tbody style="margin: 0px; padding: 0px;">
                        <tr style="margin: 0px; padding: 0px;">
                            <td style="margin: 0px; padding: 0px; font-size: 13px;"><span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);"><strong style="margin: 0px; padding: 0px;"><em style="margin: 0px; padding: 0px;">ĐC1:SỐ 6 Trần Văn Ơn,</em> TDM, BÌNH DƯƠNG</strong></span></td>
                        </tr>
                    </tbody>
                </table>
                <p style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Arial; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);"><strong style="margin: 0px; padding: 0px;">HOTLINE: &nbsp;<em style="margin: 0px; padding: 0px;">Mr. Chánh : </em><span style="margin: 0px; padding: 0px;">0369797432</span></strong></span></p>
                <p class="auto-style20" style="margin: 0px; padding: 0px; color: rgb(255, 0, 0); font-family: Arial; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);"><strong style="margin: 0px; padding: 0px; color: #FF0000;">EMAIL: </strong></span><strong>maivanchanh321@gmail.com</strong><span style="margin: 0px; padding: 0px; color: rgb(255, 255, 255);">aptop cu, mua laptop cu binh duong, mua laptop cu gia cao, mua laptop cu gia cao binh duong, mua laptop cu tai binh duong, laptop cu binh duong, ban laptop cu binh duong, ban laptop cu binh duong, ban laptop cu gia re, ban laptop cu gia re binh duong,mua may tinh cu, mua may tinh cu &nbsp;binh duong, mua may tinh ban, mua may in cu, u binh duong, ban may in cu binh duong, ban may tinh ban binh duong,mua laptop hu, mua xac laptop, mua laptop cu gia cao binh duong, ban laptop cu gia re binh duong</span></p>
            </td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td class="auto-style15" style="text-align: center">
               <button type="button" onclick="quay_lai()" class="auto-style28">Quay lại</button>

            </td>
            <td>&nbsp;</td>
        </tr>
    </table>
</asp:Content>
